version: '2'
services:
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  aflowz-sharing:
    container_name: aflowz-sharing
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8077:8069"
    volumes:
      - odoo-odoo_aflowz_sharing-data:/var/lib/odoo
      - ./config_aflowz_sharing:/etc/odoo
      - ./aflowz_sharing:/mnt/aflowz_sharing_addons
    command: odoo --dev=reload

volumes:
  odoo-odoo_aflowz_sharing-data:
  odoo-db-data: